version: '3.9'

services:
  db:
    container_name: agriculture-administration-db-container
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: adi
      POSTGRES_DB: agriculture-administration-db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
  keycloak:
    container_name: keycloak-agro-admin
    image: quay.io/keycloak/keycloak:24.0.2
    command:
      - start-dev
    ports:
      - "9090:8080"
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
      - ./keycloak_data:/opt/keycloak/data/h2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: