# Use postgres/example user/password credentials
version: '3.9'

services:
#  app:
#    image: 'agro-admin-be'
#    build:
#      context: .
#    container_name: agro-admin-be
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
#    networks:
#      - agro-admin-network
  db:
    container_name: agriculture-administration-db-container
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: adi
      POSTGRES_DB: agro-admin-db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - agro-admin-network
  azure_blob_storage:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    container_name: agro-admin-blob-storage
    environment:
      AZURE_STORAGE_ACCOUNT: 'adi'
      AZURE_STORAGE_KEY: 'key'
      AZURITE_ACCOUNTS: 'adi:key'
    ports:
      - '10000:10000'
      - '10001:10001'
      - '10002:10002'
    volumes:
      - ./azurite:/workspace
    networks:
      - 'agro-admin-network'

#  keycloak:
#    container_name: keycloak-agro-admin
#    image: quay.io/keycloak/keycloak:24.0.2
#    ports:
#      - 9090:8080
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    networks:
#      - agro-admin-network
#    command:
#      - "start-dev"
#    volumes:
#      - ./keycloak:/opt/jboss/keycloak/standalone/data/
volumes:
  postgres:
  sqlserver:
  keycloak:
networks:
  agro-admin-network: