# Use postgres/example user/password credentials
version: '3.9'

services:
#  app:
#    image: 'agro-admin-be'
#    build:
#      context: .
#    container_name: agro-admin-be
#    depends_on:
#      - db
#    ports:
#      - "8080:8080"
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    container_name: agro-admin-db
    ports:
      - '1433:1433'
    environment:
      # Username is 'SA'
      MSSQL_SA_PASSWORD: 'passwordAAA111!!!'
      ACCEPT_EULA: 'Y'
      MSSQL_TLS_VERSION: '1.0'  # Disables enforcing higher TLS versions
      MSSQL_DISABLE_ENCRYPTION: 'true'  # Disables encryption (optional, may not always apply)
    volumes:
      - sqlserver:/var/opt/mssql

volumes:
  sqlserver: