[versions]
spring-boot = "3.3.1"
spring-dependency-management = "1.1.5"
openapi-starter-webmvc-ui = "2.5.0"
openapi-starter-webflux-ui = "2.5.0"
[libraries]
jdbc = { group = "org.springframework.boot", name = "spring-boot-starter-data-jdbc" }
jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
flyway-database-postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql" }
lombok = { group = "org.projectlombok", name = "lombok" }
postgresql = { group = "org.postgresql", name = "postgresql" }
openapi-starter-webmvc-ui = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui",version.ref="openapi-starter-webmvc-ui" }
openapi-starter-webflux-ui = { group = "org.springdoc", name = "springdoc-openapi-starter-webflux-ui",version.ref="openapi-starter-webflux-ui" }
[plugins]
java = { id = "java" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
[bundles]
openapi = ["openapi-starter-webflux-ui","openapi-starter-webmvc-ui"]